name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Build
      run: |
        npm ci
        npm run build
    - name: Install Surge
      run: npm install -g surge
    - name: Deploy
      run: npx surge ./dist ${{secrets.surge_domain}} --token ${{secrets.surge_token}}
